package model.db;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName = "contact")
public class ContactDB {

    private String id;
    private String accountNumber;
    private String name;
    private Date createdAt;

    public ContactDB(String accountNumber, String name) {
        this.accountNumber = accountNumber;
        this.name = name;
        this.createdAt = new Date();
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public ContactDB setId(String id) {
        this.id = id;
        return this;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public ContactDB setName(String name) {
        this.name = name;
        return this;
    }

    @DynamoDBAttribute
    public String getAccountNumber() {
        return accountNumber;
    }

    public ContactDB setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }

    @DynamoDBAttribute
    public Date getCreatedAt() {
        return createdAt;
    }

    public ContactDB setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
        return this;
    }
}
